In [1]:
import gym
import minihack
import numpy as np
import matplotlib.pyplot as plt
import IPython.display as display

import LibraryRiccardo

# create the environment
env = gym.make("MiniHack-ExploreMaze-Easy-Mapped-v0")

# reset it to initial state
state = env.reset()

# render the environment
env.render()


Hello Agent, welcome to NetHack!  You are a chaotic male human Rogue.           
                                                                                
                                                                                
                                                                                
---     ----      ---                                                           
|.       ..        .|                                                           
|.... ..... ........|                                                           
|..     .>.     . ..|                                                           
|.......... ... . ..|                                                           
|.      ... . .   ..|                                                           
|............ . ....|                                                           
|..      ..   . . ..|                                                           
|@......... ..... ..|      

In [2]:
for i in env.actions: print(i)

#This method do a command. For choosing a command, you have to specify index of this command inside env.actions (env.actions is tuple of actions)
s, _, _, _ = env.step(0)

CompassDirection.N
CompassDirection.E
CompassDirection.S
CompassDirection.W
CompassDirection.NE
CompassDirection.SE
CompassDirection.SW
CompassDirection.NW
Command.OPEN
Command.KICK
Command.SEARCH
Command.EAT


In [3]:
Result = env.render()


                                                                                
                                                                                
                                                                                
                                                                                
---     ----      ---                                                           
|.       ..        .|                                                           
|.... ..... ........|                                                           
|..     .>.     . ..|                                                           
|.......... ... . ..|                                                           
|.      ... . .   ..|                                                           
|............ . ....|                                                           
|@.      ..   . . ..|                                                           
|<......... ..... ..|      

In [4]:
#Result = env.render()

for i in state:
    print(state[i])
    print(len(state[i]))
    print(len(state[i][0]))
    print("*"*100)

#print(type(Result))

[[2359 2359 2359 ... 2359 2359 2359]
 [2359 2359 2359 ... 2359 2359 2359]
 [2359 2359 2359 ... 2359 2359 2359]
 ...
 [2359 2359 2359 ... 2359 2359 2359]
 [2359 2359 2359 ... 2359 2359 2359]
 [2359 2359 2359 ... 2359 2359 2359]]
21
79
****************************************************************************************************
[[32 32 32 ... 32 32 32]
 [32 32 32 ... 32 32 32]
 [32 32 32 ... 32 32 32]
 ...
 [32 32 32 ... 32 32 32]
 [32 32 32 ... 32 32 32]
 [32 32 32 ... 32 32 32]]
21
79
****************************************************************************************************
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
21
79
****************************************************************************************************
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
21
79
*************************************************

TypeError: object of type 'numpy.int64' has no len()

In [7]:
state["chars"]

array([[32, 32, 32, ..., 32, 32, 32],
       [32, 32, 32, ..., 32, 32, 32],
       [32, 32, 32, ..., 32, 32, 32],
       ...,
       [32, 32, 32, ..., 32, 32, 32],
       [32, 32, 32, ..., 32, 32, 32],
       [32, 32, 32, ..., 32, 32, 32]], dtype=uint8)